export const TASK_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED'
}

export const TASK_UPDATE_TYPES = {
  STATUS: 'STATUS'
}

export const STORE = {
  LOCAL_STORAGE_KEY: 'CATCH_THE_FROG_STORE'
}
